import React from "react";
import { createRoot } from "react-dom/client";
import "@fontsource/figtree/400.css";
import "@fontsource/figtree/500.css";
import "@fontsource/figtree/600.css";
import "@fontsource/figtree/700.css";
import "@fontsource/dm-mono/400.css";
import EditorialApp from "./EditorialApp";
import "./discovery.css";
import "./editorial.css";
createRoot(document.getElementById("root")).render(<EditorialApp />);
